// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mmadHCpQYKSI9GZ3vtv72wG-Te6WBII',
    appId: '1:211289236675:web:d377a233823e2e3895ae76',
    messagingSenderId: '211289236675',
    projectId: 'openfitnesstracker-d8fgp5',
    authDomain: 'openfitnesstracker-d8fgp5.firebaseapp.com',
    storageBucket: 'openfitnesstracker-d8fgp5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDBqXRO-INfqBksGkX7e4Out3mlQTe8Ug',
    appId: '1:211289236675:android:b606ed6eb4caf3b195ae76',
    messagingSenderId: '211289236675',
    projectId: 'openfitnesstracker-d8fgp5',
    storageBucket: 'openfitnesstracker-d8fgp5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2-r7J87hCZYV_GQFYHpyQiVmu0iDbPQU',
    appId: '1:211289236675:ios:2629e0e27f2f084e95ae76',
    messagingSenderId: '211289236675',
    projectId: 'openfitnesstracker-d8fgp5',
    storageBucket: 'openfitnesstracker-d8fgp5.appspot.com',
    androidClientId: '211289236675-4fdbrih5492p02ssr3q1rf1ef2q9nkrb.apps.googleusercontent.com',
    iosClientId: '211289236675-ukl69kitoa47hbvfi84kku4ka9s6buf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.openFitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2-r7J87hCZYV_GQFYHpyQiVmu0iDbPQU',
    appId: '1:211289236675:ios:2629e0e27f2f084e95ae76',
    messagingSenderId: '211289236675',
    projectId: 'openfitnesstracker-d8fgp5',
    storageBucket: 'openfitnesstracker-d8fgp5.appspot.com',
    androidClientId: '211289236675-4fdbrih5492p02ssr3q1rf1ef2q9nkrb.apps.googleusercontent.com',
    iosClientId: '211289236675-ukl69kitoa47hbvfi84kku4ka9s6buf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.openFitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2mmadHCpQYKSI9GZ3vtv72wG-Te6WBII',
    appId: '1:211289236675:web:d377a233823e2e3895ae76',
    messagingSenderId: '211289236675',
    projectId: 'openfitnesstracker-d8fgp5',
    authDomain: 'openfitnesstracker-d8fgp5.firebaseapp.com',
    storageBucket: 'openfitnesstracker-d8fgp5.appspot.com',
  );
}
