// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpPfPHy_Nn_uKflJyChZlwT4elEdS5bqY',
    appId: '1:211289236675:web:ddcf522bdd4da19795ae76',
    messagingSenderId: '211289236675',
    projectId: 'openfitnesstracker-d8fgp5',
    authDomain: 'openfitnesstracker-d8fgp5.firebaseapp.com',
    storageBucket: 'openfitnesstracker-d8fgp5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEJwdQoi3Qh9F2MnznGwOTwGRmbI8_xXU',
    appId: '1:211289236675:android:501324e55afa113f95ae76',
    messagingSenderId: '211289236675',
    projectId: 'openfitnesstracker-d8fgp5',
    storageBucket: 'openfitnesstracker-d8fgp5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgmL5HLmmo64HFu_a7G9WeJwy8CiKcZSg',
    appId: '1:211289236675:ios:2629e0e27f2f084e95ae76',
    messagingSenderId: '211289236675',
    projectId: 'openfitnesstracker-d8fgp5',
    storageBucket: 'openfitnesstracker-d8fgp5.appspot.com',
    androidClientId: '211289236675-4fdbrih5492p02ssr3q1rf1ef2q9nkrb.apps.googleusercontent.com',
    iosClientId: '211289236675-ukl69kitoa47hbvfi84kku4ka9s6buf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.openFitnessTracker',
  );
}
